about:
  home: http://pypi.python.org/pypi/d2to1
  license: BSD License
  summary: Allows using distutils2-like setup.cfg files for a package's metadata with
    a distribute/setuptools setup.py
build:
  number: 0
  preserve_egg_dir: true
package:
  name: d2to1
  version: 0.2.12.post1
requirements:
  build:
  - python
  - setuptools
  - setuptools
  run:
  - python
  - setuptools
  - setuptools
source:
  fn: d2to1-0.2.11.tar.gz
  md5: 1ba7e64ead23cbf104993122f0871030
  url: https://pypi.python.org/packages/source/d/d2to1/d2to1-0.2.12.post1.tar.gz
test:
  imports:
  - d2to1
  - d2to1.extern
