package:
  name: pyvo
  version: 0.2.1+290159

source:
  git_url: https://github.com/pyvirtobs/pyvo.git
  git_branch: master
  
build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - numpy
    - astropy

  run:
    - python
    - numpy
    - astropy

about:
  home: http://www.astropy.org/
  license: BSD
