about:
  home: http://ejeschke.github.com/ginga
  license: BSD License
  summary: An astronomical image viewer and toolkit.
build:
  number: 0
package:
  name: ginga
  version: 2.5.20160420043855
requirements:
  build:
  - python
  - setuptools
  - numpy
  - patch
  run:
  - python
  - numpy
source:
  fn: ginga-2.5.20160420043855.tar.gz
  md5: 3f2af4014b60feb26dcf9408b59f3b3d
  patches:
  - fix-unicode.patch
  url: https://pypi.python.org/packages/31/33/5ab3c0c437556fe0d6d623e9af5526e074ef3b20b25d05cfa6cf3d10f15b/ginga-2.5.20160420043855.tar.gz
test:
  imports:
  - ginga
  - ginga.aggw
  - ginga.cairow
  - ginga.canvas
  - ginga.cvw
  - ginga.doc
  - ginga.gtkw
  - ginga.gtkw.plugins
  - ginga.gtkw.tests
  - ginga.icons
  - ginga.misc
  - ginga.misc.plugins
  - ginga.mockw
  - ginga.mplw
  - ginga.qtw
  - ginga.qtw.plugins
  - ginga.qtw.tests
  - ginga.tests
  - ginga.tkw
  - ginga.util
  - ginga.web
  - ginga.web.pgw
  - ginga.web.pgw.js
  - ginga.web.pgw.templates
