package:
  name: ipycache

source:
  git_url: https://github.com/vascotenner/ipycache.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  commands:
    - git clone --depth=50 https://github.com/vascotenner/ipycache.git source
    - cd source
    - nosetests
    - python ipynb_runner.py -v -s examples/example.ipynb  # [not win]
    - python ipynb_runner.py -v -s examples/example_outputs.ipynb  # [not win]
    - cd ..

  requires:
    - nose
    - numpy
    - matplotlib
    - ipython
    - nbformat
    - ipykernel

about:
  home: http://packages.python.org/ipycache
  license: BSD License
  summary: 'Defines a %%cache cell magic in the IPython notebook to cache results of long-lasting computations in a persistentpickle file.'

extra:
  recipe-maintainers:
    - jochym
