about:
  home: https://github.com/pypa/setuptools_scm/
  license: MIT License
  summary: the blessed package to manage your versions by scm tags
build:
  number: 0
package:
  name: setuptools_scm
  version: 1.11.0
requirements:
  build:
  - python
  - setuptools
  run:
  - python
source:
  git_tag: v1.11.0
  git_url: https://github.com/pypa/setuptools_scm.git
test:
  imports:
  - setuptools_scm
