about:
  home: https://wiki.fysik.dtu.dk/ase
  license: LGPLv2.1+
  summary: Atomic Simulation Environment
build:
  number: 2
package:
  name: python-ase
  version: 3.10.0
requirements:
  build:
  - python
  - numpy
  - scipy
  run:
  - python
  - numpy
  - matplotlib
  - scipy
source:
  fn: ase-3.10.0.tar.gz
  md5: 87854bb3b43d1a57b0c3db4b5addcee3
  url: https://pypi.python.org/packages/source/a/ase/ase-3.10.0.tar.gz
test:
  commands:
  - python -m ase.test
  imports:
  - ase
  - ase.calculators
  - ase.cli
  - ase.cluster
  - ase.data
  - ase.db
  - ase.dft
  - ase.gui
  - ase.io
  - ase.lattice
  - ase.lattice.spacegroup
  - ase.md
  - ase.optimize
  - ase.tasks
  - ase.test
  - ase.test.abinit
  - ase.test.aims
  - ase.test.castep
  - ase.test.elk
  - ase.test.exciting
  - ase.test.fio
  - ase.test.fleur
  - ase.test.gaussian
  - ase.test.gromacs
  - ase.test.jacapo
  - ase.test.nwchem
  - ase.test.tasks
  - ase.test.vasp
  - ase.transport
  - ase.utils
  - ase.vibrations
  - ase.visualize
  requires:
  - qt
