about:
  home: https://wiki.fysik.dtu.dk/ase
  license: LGPLv2.1+
  summary: Atomic Simulation Environment
build:
  number: 2
package:
  name: python-ase
  version: 3.11.0
requirements:
  build:
  - python
  - numpy
  - scipy
  run:
  - python
  - numpy
  - matplotlib
  - scipy
source:
  fn: ase-3.11.0.tar.gz
  md5: d7afe49d5beb1b1c38d60b1e3dd4e763
  url: https://pypi.python.org/packages/fc/7b/558e7321f7a879c034ead5d10789b9d6f41beabaee0b156e807c19422ad0/ase-3.11.0.tar.gz
test:
  commands:
    - python -m ase.test

  requires:
    - qt
