{% set name = "libspg" %}
{% set version = "1.11.0" %}
{% set sha256 = "e4befe27473a69b7982597760d6838cc48d9ef7b624a439436a17f5487f78f51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/atztogo/spglib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}

about:
  home: https://atztogo.github.io/spglib/
  license: BSD-3-clause
  license_family: BSD
  summary: 'Space symmetry groups library.'

  description: |
    libspg is a library for finding and handling crystal symmetries.
  doc_url: https://atztogo.github.io/spglib/
  dev_url: https://github.com/atztogo/spglib

extra:
  recipe-maintainers:
    - jochym
    - atztogo