package:
  name: de421
  version: "2008.1"

source:
  fn: de421-2008.1.tar.gz
  url: https://pypi.python.org/packages/source/d/de421/de421-2008.1.tar.gz
  md5: 6b0e673d2bd49ec0ad481e20beac8f9c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - de421 = de421:main
    #
    # Would create an entry point called de421 that calls de421.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - de421

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/brandon-rhodes/python-jplephem/
  license: MIT License
  summary: 'JPL Planetary and Lunar Ephemeris DE421 for the jplephem package.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
