package:
  name: phonopy3
  version: !!str 1.10.0

source:
  #git_url: https://github.com/atztogo/phonopy.git
  url: http://downloads.sourceforge.net/project/phonopy/phonopy/phonopy-1.10/phonopy-1.10.0.tar.gz
  fn: phonopy3.tgz

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - spglib

  run:
    - python
    - numpy
    - matplotlib
    - spglib
    - yaml

test:
  # Python imports
  imports:
    - phonopy

#  commands:
#    # You can put test commands to be run here.  Use this to test that the
#    # entry points work.
#    - cd example/MgO 
#    - phonopy -f vasprun.xml-001 vasprun.xml-002
#    - phonopy -p band.conf
#    - phonopy -p --nac band.conf


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://phonopy.sourceforge.net/
  license: BSD
  summary: 'Phonon calculation with finite displacements method.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
