about:
  home: https://github.com/ipython-contrib/IPython-notebook-extensions
  license: Modified BSD License
  summary: Notebook extensions for the Jupyter/IPython notebook
build:
  number: 0

package:
  name: nbextensions
  version: 4.6+17b9a2
requirements:
  build:
  - ipython >=4
  - jupyter_client
  - jupyter_core
  - notebook
  - nbconvert
  - nbformat
  - python
  - traitlets
  - psutil
  - pyyaml
  - jupyter
  run:
  - ipython >=4
  - jupyter_client
  - jupyter_core
  - notebook
  - nbconvert
  - nbformat
  - python
  - traitlets
  - pyyaml
source:
  git_branch: master
  git_url: https://github.com/ipython-contrib/IPython-notebook-extensions.git
