package:
  name: unum
  version: "4.1.3"

source:
  fn: Unum.zip
  url: https://pypi.python.org/packages/source/U/Unum/Unum-4.1.3.zip
  md5: 66302714c23a24b254f7e61ba427705b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - unum = unum:main
    #
    # Would create an entry point called unum that calls unum.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 3

requirements:
  build:
    - python
    - setuptools
    - nose

  run:
    - python

test:
  # Python imports
  imports:
    - tests
    - unum
    - unum.units
    - unum.units.custom
    - unum.units.others
    - unum.units.si

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: http://bitbucket.org/kiv/unum/
  license: LGPL
  summary: 'Units in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
