about:
  home: https://wiki.fysik.dtu.dk/ase
  license: LGPLv2.1+
  summary: Atomic Simulation Environment
build:
  number: 0
package:
  name: ase
  version: 3.12.0
requirements:
  build:
    - python
    - numpy
    - scipy
  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - anaconda-build
source:
  fn: ase-3.12.0.tar.gz
  md5: adf1915e219d36421aa488fffed1457e
  url: https://pypi.python.org/packages/ab/d4/4fb1a390d6ca8c4b190285eaecbb0349d3989befd5e670dc14751c715575/ase-3.12.0.tar.gz
test:
  commands:
    - cat /home/dev/build_script.sh
    - python -m ase.test
  requires:
    - qt
