package:
  name: jplephem
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/brandon-rhodes/python-jplephem.git
  git_tag: v2.4
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jplephem = jplephem:main
    #
    # Would create an entry point called jplephem that calls jplephem.main()


requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - jplephem

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://pypi.python.org/pypi/jplephem
  license: MIT License
  summary: 'Use a JPL ephemeris to predict planet positions.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
