package:
  name: spglib
  version: !!str 1.7.0

source:
  git_tag: v1.7.0
  git_url: https://github.com/atztogo/spglib.git
#  url: http://downloads.sourceforge.net/project/spglib/spglib/spglib-1.6/spglib-1.6.3.tar.gz
#  md5: 8ae328fbd0ed381355c756bffca5653a
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - spglib = spglib:main
    #
    # Would create an entry point called spglib that calls spglib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - pyspglib

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://spglib.sourceforge.net/
  license: BSD
  summary: 'This is the spglib module.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
