about:
  home: http://www.stsci.edu/resources/software_hardware/pyfits
  license: BSD License
  summary: Reads FITS images and tables into numpy arrays and manipulates FITS headers
build:
  number: 1
package:
  name: pyfits
  version: 3.4.0
requirements:
  build:
  - python
  - setuptools
  - numpy
  - stsci.distutils
  - d2to1
  run:
  - python
  - numpy
source:
  git_tag: v3.4.0
  git_url: https://github.com/spacetelescope/PyFITS.git
test:
  imports:
  - pyfits
