package:
  name: pyfits
  version: 3.3.0

source:
  git_url: https://github.com/spacetelescope/PyFITS.git
  git_tag: v3.3.0

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyfits = pyfits:main
    #
    # Would create an entry point called pyfits that calls pyfits.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 3

requirements:
  build:
    - python
    - setuptools
    - numpy
    - stsci.distutils
    - d2to1

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - pyfits

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.stsci.edu/resources/software_hardware/pyfits
  license: BSD License
  summary: 'Reads FITS images and tables into numpy arrays and manipulates FITS headers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
